name: 'dbt_conceptual_demo'
version: '1.0.0'
config-version: 2

profile: 'dbt_conceptual_demo'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

# =============================================================================
# dbt-conceptual configuration
# =============================================================================
vars:
  dbt_conceptual:
    # Directory where conceptual model definition lives
    conceptual_path: "models/05_conceptual"

    # List of folders for staging/silver layer models
    silver_paths:
      - "models/03_silver"

    # List of folders for gold/marts layer models
    gold_paths:
      - "models/04_gold"

# =============================================================================
# Model configurations
# =============================================================================
models:
  dbt_conceptual_demo:
    01_bronze:
      +schema: bronze
      +materialized: incremental
      +tags:
        - bronze
        - ingestion
    02_staging:
      +schema: staging
      +materialized: view
      +tags:
        - staging
    03_silver:
      +schema: silver
      +materialized: incremental
      +tags:
        - silver
    04_gold:
      +schema: gold
      +materialized: table
      +tags:
        - gold
